package com.justinmobile.tsm.cms2ac;

public interface SessionStatus {

	/** 异常终止状态 */
	int TERMINATE = -1;

	/** 空状态 */
	int DUPLICATE_STATUS = 0;

	/** 起始状态 */
	int INIT = 1;

	/** 成功完成 */
	int COMPLETED = 2;

	/** 预处理完成 */
	int PRE_OPERATION_SUCCESS = 3;

	/** 通知业务平台操作结果 */
	int OPERATE_NOTIFY = 4;

	/** 获取卡片注册的触发指令 */
	int REG_SELECT_ISD = 1001;

	int REG_INIT_UPDATE = 1002;

	int REG_EXT_AUTH = 1003;

	int REG_WRITE_TOEKN = 1004;

	int LOGIN_SELECT_ISD = 1101;

	int LOGIN_INIT_UPDATE = 1102;

	int LOGIN_EXT_AUTH = 1103;

	int LOGIN_READ_TOEKN = 1104;

	/** 获取开通BIP的触发指令 */
	int CONTROL_BIP_GET_OPEN_TRIGGER = 2001;

	int CONTROL_BIP_GET_OPEN_CONFIRM = 2002;

	int CONTROL_BIP_SEND_CLOSE_REQ = 2003;

	int OPEN_RW_WAIT_OPEN_REQ = 2101;

	/** 开始创建安全域 */
	int CREATE_SD_START_UP = 3001;

	int CREATE_SD_SPACE_CMD = 3002;

	int CREATE_SD_INSTALL_CMD = 3003;

	int CREATE_SD_SELECT_ISD_CMD = 3101;

	int CREATE_SD_INITUPDATE_CMD = 3102;

	int CREATE_SD_EXTAUTH_CMD = 3103;

	int CREATE_SD_END_INSTALL = 3104;

	/** 开始删除安全域 */
	int DELETE_SD_START_UP = 4001;

	int DELETE_SD_DELETE_CMD = 4003;

	int DELETE_SD_SELECT_ISD_CMD = 4101;

	int DELETE_SD_INITUPDATE_CMD = 4102;

	int DELETE_SD_EXTAUTH_CMD = 4103;

	/** 开始下载应用 */
	int DOWNLOAD_APP_START_UP = 5001;

	int DOWNLOAD_APP_LF_SD_SPACE_CMD = 5002;

	int DOWNLOAD_APP_INSTALL_LF_SD_CMD = 5003;

	int DOWNLOAD_APP_LF_SD_PUT_KEY_CMD = 5004;

	int DOWNLOAD_APP_LF_SD_PERSO_CMD = 5005;

	int DOWNLOAD_APP_APP_SD_SPACE_CMD = 5006;

	int DOWNLOAD_APP_INSTALL_APP_SD_CMD = 5007;

	int DOWNLOAD_APP_APP_SD_PUT_KEY_CMD = 5008;

	int DOWNLOAD_APP_APP_SD_PERSO_CMD = 5009;

	int DOWNLOAD_APP_SPACE_CMD = 5010;

	int DOWNLOAD_APP_GET_DIR_TRIGGER = 5011;

	int DOWNLOAD_APP_GET_DIR_COMFIRM = 5012;

	int DOWNLOAD_APP_RECEIVE_DIR_RESULT = 5013;

	int DOWNLOAD_APP_GET_AID_BIND = 5014;

	int DOWNLOAD_APP_INSTALL_LOAD_CMD = 5015;

	int DOWNLOAD_APP_LOAD_CMD = 5016;

	int DOWNLOAD_APP_INSTALL_INSTALL_CMD = 5017;

	int DOWNLOAD_APP_INSTALL_EXTRADITION_CMD = 5018;

	int DOWNLOAD_APP_START_PERSO = 5019;

	int DOWNLOAD_APP_PESO_APDU_CMD = 5020;

	int DOWNLOAD_APP_PESO_APDU_RSP = 5021;

	int DOWNLOAD_APP_END_PERSO = 5022;

	int DOWNLOAD_APP_INSTALL_PERSONALIZATION_DIR_CMD = 5023;

	int DOWNLOAD_APP_INSTALL_PERSONALIZATION_BINDAID_CMD = 5024;

	int DOWNLOAD_APP_CREATE_LF_SD_SELECT_ISD_CMD = 5101;

	int DOWNLOAD_APP_INITUPDATE_CREATE_LF_SD_CMD = 5102;

	int DOWNLOAD_APP_EXTAUTH_CREATE_LF_SD_CMD = 5103;

	int DOWNLOAD_APP_SELECT_LF_SD_CMD = 5104;

	int DOWNLOAD_APP_INITUPDATE_LF_SD_CMD = 5105;

	int DOWNLOAD_APP_EXTAUTH_LF_SD_CMD = 5106;

	int DOWNLOAD_APP_CREATE_APP_SD_SELECT_ISD_CMD = 5107;

	int DOWNLOAD_APP_INITUPDATE_CREATE_APP_SD_CMD = 5108;

	int DOWNLOAD_APP_EXTAUTH_CREATE_APP_SD_CMD = 5109;

	int DOWNLOAD_APP_SELECT_APP_SD_CMD = 5110;

	int DOWNLOAD_APP_INITUPDATE_APP_SD_CMD = 5111;

	int DOWNLOAD_APP_EXTAUTH_APP_SD_CMD = 5112;

	int DOWNLOAD_APP_SELECT_USIM_APP_CMD = 5113;

	int DOWNLOAD_APP_LOAD_SELECT_ISD_CMD = 5114;

	int DOWNLOAD_APP_INITUPDATE_LOAD_CMD = 5115;

	int DOWNLOAD_APP_EXTAUTH_LOAD_CMD = 5116;

	int DOWNLOAD_APP_SELECT_PERSO_APP_CMD = 5117;

	int DOWNLOAD_APP_OPEN_APP_BIP_CMD = 5201;

	int DOWNLOAD_APP_CLOSE_APP_BIP_CMD = 5202;

	int DOWNLOAD_APP_GET_AID_BIND_CONFIRM = 5205;

	int DOWNLOAD_APP_DIR_CREATED = 5206;

	int DOWNLOAD_APP_DIR_NOT_EXIST = 5207;

	int DOWNLOAD_APP_END_LOAD = 5301;

	int DOWNLOAD_APP_BEGIN_LOAD = 5302;

	int DOWNLOAD_APP_BEGIN_PERSO = 5303;

	int DOWNLOAD_APP_PERSO = 5304;

	/** 开始删除应用 */
	int DELETE_APP_START_UP = 6001;

	int DELETE_APP_DELETE_CMD = 6002;

	int DELETE_APP_DELETE_SD_CMD = 6003;

	int DELETE_APP_SELECT_SD_CMD = 6101;

	int DELETE_APP_INITUPDATE_CMD = 6102;

	int DELETE_APP_EXTAUTH_CMD = 6103;

	int DELETE_APP_UBIND_CMD = 6104;

	int DELETE_APP_UBIND_CONFIRM_CMD = 6105;

	int DELETE_APP_START_CMD = 6106;

	int DELETE_APP_INSTALL_PERSONALIZATION_CMD = 6107;

	int DELETE_APP_END_DELETE_LOAD_FILE = 6201;

	int DELETE_APP_DELETE_LOAD_FILE_CMD = 6202;

	int DELETE_APP_DELETE_APPLET_CMD = 6203;

	int DELETE_APP_END_DELETE_LF_SD = 6204;

	int DELETE_APP_END_DELETE_APP = 6205;

	int DELETE_APP_READ_PERSO_DATA = 6206;

	int DELETE_APP_OPERATION_NOTIFY = 6207;

	/** 开始锁定应用 */
	int LOCK_APP_START_UP = 7001;

	int LOCK_APP_LOCK_CMD = 7002;

	int LOCK_APP_SELECT_SD_CMD = 7101;

	int LOCK_APP_INITUPDATE_CMD = 7102;

	int LOCK_APP_EXTAUTH_CMD = 7103;

	/** 开始解锁应用 */
	int UNLOCK_APP_START_UP = 8001;

	int UNLOCK_APP_UNLOCK_CMD = 8002;

	int UNLOCK_APP_SELECT_SD_CMD = 8101;

	int UNLOCK_APP_INITUPDATE_CMD = 8102;

	int UNLOCK_APP_EXTAUTH_CMD = 8103;

	/** 开始个人化 */
	int PERSONALIZE_APP_START_UP = 9001;

	int PERSONALIZE_APP_APDU_CMD = 9002;

	int PERSONALIZE_APP_APDU_RSP = 9003;

	int PERSONALIZE_APP_END_PERSO = 9004;

	int PERSONALIZE_APP_BEGIN_PERSON = 9005;

	int PERSONALIZE_APP_PESO_APDU_RSP = 9006;

	int PERSONALIZE_APP_SELECT_APP_CMD = 9101;

	int PERSONALIZE_APP_OPEN_APP_BIP_CMD = 9201;

	int PERSONALIZE_APP_CLOSE_APP_BIP_CMD = 9202;

	int PERSONALIZE_APP_INITUPDATE_APP_SD_CMD = 9301;

	int PERSONALIZE_APP_SELECT_APP_SD_CMD = 9302;

	int PERSONALIZE_APP_EXTAUTH_SD_CMD = 9303;

	int PERSONALIZE_APP_EXTAUTH_APP_SD_CMD = 9304;

	int PERSONALIZE_APP_INSTALL_PERSO_CMD = 9305;

	int PERSONALIZE_APP_SELECT_CMD = 9306;

	/** 开始个更新安全域密钥 */
	int UPDATE_SD_KEY_START_UP = 10001;

	int UPDATE_SD_KEY_PUT_KEY_CMD = 10002;

	int UPDATE_SD_KEY_PERSO_CMD = 10003;

	int UPDATE_SD_KEY_SELECT_SD_CMD = 10101;

	int UPDATE_SD_KEY_INITUPDATE_CMD = 10102;

	int UPDATE_SD_KEY_EXTAUTH_CMD = 10103;

	/** 异常处理，信息同步 */
	int SYNC_CARD_START_UP = 16001;

	int SYNC_CARD_SELECT_ISD_CMD = 16002;

	int SYNC_CARD_INITUPDATE_CMD = 16003;

	int SYNC_CARD_EXTAUTH_CMD = 16004;

	int SYNC_CARD_GET_PACKAGE_STATUS = 16005;

	int SYNC_CARD_GET_APPLET_STATUS = 16006;

	int SYNC_CARD_DELETE_LOAD_FILE_CMD = 16007;

	int SYNC_CARD_DELETE_APPLET_CMD = 16008;

	/** 开始安全域同步 */
	int SYN_SECURITY_DOMAIN = 11000;

	/** 开始应用同步 */
	int SYN_APPLICATION = 12000;

	/** 卡空间同步完成 */
	int SYN_CAED_SPACE_START = 13000;

	/** 获取卡片空间数据 */
	int SYN_CAED_SPACE_GET_DATA = 13001;

	/** 卡空间同步完成 */
	int SYN_CAED_SPACE_END = 13002;

	/** 请求业务平台预订购 */
	int BUSINESS_PRIOR_ORDER = 14001;
	/** 请求业务平台扣费 */
	int BUSINESS_DEBUCT_CHARGE = 14002;
	/** 请求业务平台订购 */
	int BUSINESS_ORDER_PRODUCT = 14003;
	/** 业务冲正 */
	int BUSINESS_CORRECT = 14004;

	/** 请求Token */
	int ACQUIRE_TOKNE = 15001;

	int UPDATE_APP_END_DELETE = 16001;

	int UPDATE_APP_END_UPDATE = 16002;

	int UPDATE_APP_BEGIN_CLEAE_APPLET = 160003;

	int UPDATE_APP_BEGIN_DOWNLOAD = 16004;

	int UPDATE_APP_READ_DATA = 16005;

	int DELETE_APPLET_SELECT_CMD = 18001;

	int DELETE_APPLET_INIT_UPDATE_CMD = 18002;

	int DELETE_APPLET_EXT_AUTH_CMD = 18003;

	int DELETE_APPLET_DELETE = 18004;

	int REPLACE_MOBILE_NO_NOTIFIED = 19001;

	int REPLACE_MOBILE_NO_SELECT = 190002;

	int REPLACE_MOBILE_NO_INIT_UPDATE = 190003;

	int REPLACE_MOBILE_NO_EXT_AUTH = 190004;

	int REPLACE_MOBILE_NO_STORE_MOBILE_NO = 190005;
}
